project:
  type: website
  output-dir: docs

website:
  title: "Workshop về IDM"
  navbar:
    left:
      - href: index.qmd
        text: Giới thiệu
      - href: Note.qmd
        text: Bài học

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

