project:
  type: website
  output-dir: docs

website:
  title: "Workshop về IDM"
  navbar:
    left:
      - text: "Giới thiệu"
        file: index.qmd
      - text: "Lý thuyết"
        file: Note.qmd
      - text: "Bài thực hành 1"
        file: Practice_1.qmd
      - text: "Bài thực hành 2"
        file: Practice_2.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

