project:
  type: website
  output-dir: docs

website:
  title: "Workshop về IDM"
  navbar:
    left:
      - text: "Giới thiệu"
        file: index.qmd
      - text: "Lý thuyết 1"
        file: Note.qmd
      - text: "Lý thuyết 2"
        file: Day_2.qmd
      - text: "Thực hành 1"
        file: Practice_1.qmd
      - text: "Thực hành 2"
        file: Practice_2.qmd

format:
  html:
    theme: simplex
    css: css/style.css
    toc: true

editor: visual

