---
title: "Giới thiệu khoá học"
date: "`r Sys.Date()`"
language: vn.yml
format: 
  html:
    css: [css/style.css, css/webex.css]
    toc: true
    toc-float: true
    toc-depth: 2
    number-sections: true
    number-depth: 3
    include-after-body: js/webex.js
    self-contained: true
bibliography: references.bib
csl: the-new-england-journal-of-medicine.csl
---

### Giới thiệu chung {-}

Để đánh giá và kiểm soát dịch bệnh truyền nhiễm một cách hiệu quả, việc ước tính được mức độ lây nhiễm của bệnh trong cộng đồng, thông qua chỉ số hệ số lây nhiễm, có vai trò rất quan trọng. Ngoài việc giúp đánh giá được diễn tiến hiện tại của dịch, hệ số lây nhiễm còn có thể được dùng để so sánh và đánh giá hiệu quả của các biện pháp can thiệp trong các tình huống khác nhau, từ đó đóng góp nguồn thông tin quan trọng để cơ quan chức năng lựa chọn và đưa ra giải pháp phòng ngừa và kiểm soát dịch bệnh tối ưu. Để ước tính được hệ số lây nhiễm và ứng dụng hiệu quả chỉ số dịch tễ này, chúng ta cần đến các mô hình toán học về dịch tễ học bệnh truyền nhiễm. Trong thời gian gần đây, đặc biệt là trong đại dịch COVID-19, các mô hình này đã được ứng dụng rộng rãi và là công cụ đóng góp đắc lực vào nỗ lực kiểm soát dịch bệnh truyền nhiễm tại nhiều quốc gia trên thế giới.

Từ đề xuất của lãnh đạo HCDC nhằm từng bước giới thiệu và ứng dụng công cụ này tại đơn vị, workshop "Giới thiệu về mô hình toán học trong đánh giá và kiểm soát dịch bệnh truyền nhiễm" được tổ chức với 2 mục tiêu chính:

-   Giới thiệu một số nguyên tắc cơ bản trong việc xây dựng và ứng dụng mô hình toán học trong đánh giá và kiểm soát dịch bệnh truyền nhiễm.

-   Giới thiệu định nghĩa, cách tính toán và ứng dụng hệ số lây nhiễm trong đánh giá và kiểm soát dịch bệnh truyền nhiễm.

### Chương trình  {-}

+-------------+---------------+-------------------------------------------+----------------------------------+
| Ngày        | Giờ           | Nội dung                                  | Giảng viên                       |
+=============+===============+===========================================+==================================+
| Thứ tư      | 14:00 - 15:00 | *Lý thuyết 1*                             | Phùng Khánh Lâm                  |
|             |               |                                           |                                  |
| 01/03/2023  |               | **Giới thiệu về mô hình toán học**        |                                  |
+-------------+---------------+-------------------------------------------+----------------------------------+
|             | 15:00 - 15:15 | Giải lao                                  |                                  |
+-------------+---------------+-------------------------------------------+----------------------------------+
|             | 15:15 - 16:00 | *Thực hành 1*                             | Ong Phúc Thịnh & Phùng Khánh Lâm |
|             |               |                                           |                                  |
|             |               | **Thiết kế mô hình**                      |                                  |
+-------------+---------------+-------------------------------------------+----------------------------------+
| Thứ năm     | 14:00 - 15:00 | *Lý thuyết 2*                             | Ong Phúc Thịnh                   |
|             |               |                                           |                                  |
| 02/03/2023  |               | **Tính toán và ứng dụng hệ số lây nhiễm** |                                  |
+-------------+---------------+-------------------------------------------+----------------------------------+
|             | 15:00 - 15:15 | Giải lao                                  |                                  |
+-------------+---------------+-------------------------------------------+----------------------------------+
|             | 15:15 - 16:00 | *Thực hành 2*                             | Ong Phúc Thịnh & Phùng Khánh Lâm |
|             |               |                                           |                                  |
|             |               | **Tính toán hệ số lây nhiễm bằng Excel**  |                                  |
+-------------+---------------+-------------------------------------------+----------------------------------+

Nội dung khoá học được tham khảo và dựa theo cấu trúc của khoá học "Introduction to mathematical models of the Epidemiology & Control of Infectious Diseases" tại Singapore, 13-16/10/2022, do GS Azra Ghani và MRC Centre for Global Infectious Disease Analysis (Imperial College London) & Lee Kong Chian School of Medicine (Nanyang Technical University) tổ chức.

### Người trình bày {-}

* Phùng Khánh Lâm, TS.BS., giảng viên Bộ môn Dịch tễ học, Khoa Y tế công cộng, Đại học Y Dược TPHCM.
* Ong Phúc Thịnh, BS., nghiên cứu sinh tại Đại học Oxford, thành viên nhóm Mô hình toán tại Đơn vị nghiên cứu lâm sàng Đại học Oxford. 

### Slide {-}

[Lý thuyết 1](https://lampk.github.io/IDMIntro/Slide_Intro.html)

[Lý thuyết 2](https://lampk.github.io/IDMIntro/Slide_Day2.html)

[Tóm tắt và một số điểm lưu ý](https://lampk.github.io/IDMIntro/Slide_Conclusion.html)
